export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SPRINT_ACTION = 'SPRINT_ACTION';
export const USER_TYPE = 'USER_TYPE'