export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SPRINT_ACTION = 'SPRINT_ACTION';
export const USER_TYPE = 'USER_TYPE'
export const BANK_DATA = 'BANK_DATA'
export const STOP_POSTING = 'STOP_POSTING'